# Generated by Django 3.2 on 2021-06-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='breed',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='specie',
            field=models.CharField(choices=[('G', 'Gato'), ('P', 'Perro'), ('E', 'Erizo'), ('C', 'Conejo'), ('L', 'Loro'), ('TO', 'Tortuga'), ('TA', 'Tarantula'), ('O', 'Otro')], max_length=30),
        ),
    ]
